// NOTE: This error is generated by Firebase, not our app.
const firebaseAuthError = 'There is no user record corresponding to this identifier. The user may have been deleted.';

const emailSelector = '#email';
const passwordSelector = '#password';
const loginButtonSelector = '#login-btn';
const snackbarSelector = '#notifications-snackbar';

describe('authentication', () => {
  let page;

  describe('auth failures', () => {
    const badEmail = 'foo@bar.com';
    const badPassword = 'badPassword';

    beforeEach(async () => {
      page = await global.BROWSER.newPage();
      await page.goto('http://localhost:8080/#/login');
      await page.waitForSelector(emailSelector);
      await page.waitForSelector(passwordSelector);
    });

    it('should fail to login with bad username/password', async () => {
      // Attempt to login.
      await page.type(emailSelector, badEmail);
      await page.type(passwordSelector, badPassword);
      await page.click(loginButtonSelector);

      // Wait for the snackbar to popup, then verify the text.
      await page.waitForSelector(snackbarSelector);

      const text = await page.evaluate(selector =>
        document.querySelector(selector).textContent,
      snackbarSelector);

      expect(text).toContain(firebaseAuthError);
    });
  });
});
