// User action constants
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_PENDING = 'AUTH_PENDING';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';

// Notification action constants
export const NOTIFICATION_DISPLAY_ERROR = 'DISPLAY_ERROR';
export const NOTIFICATION_CONFIRM_RESET_PASSWORD = 'CONFIRM_RESET_PASSWORD';
export const NOTIFICATION_ADD = 'NOTIFICATION_ADD';
export const NOTIFICATION_REMOVE = 'NOTIFICATION_REMOVE';

// Modals
export const MODAL_CLOSE_MODAL = 'MODAL_CLOSE_MODAL';
export const MODAL_SET_MODAL = 'MODAL_SET_MODAL';
export const MODAL_SET_IMAGE_CONTEXT = 'MODAL_SET_IMAGE_CONTEXT';

// Request status
export const REQUEST_START = 'REQUEST_START';
export const REQUEST_END = 'REQUEST_END';
export const REQUEST_FAILED = 'REQUEST_FAILED';
