// User action constants
export const AUTH_AUTHENTICATION_ERROR = 'AUTH_AUTHENTICATION_ERROR';
export const AUTH_AUTHENTICATION_FAILED = 'AUTH_AUTHENTICATION_FAILED';
export const AUTH_AUTHENTICATION_SUCCESS = 'AUTH_AUTHENTICATION_SUCCESS';
export const AUTH_AUTHENTICATION_PENDING = 'AUTH_AUTHENTICATION_PENDING';

export const AUTH_AUTHORIZATION_ERROR = 'AUTH_AUTHORIZATION_ERROR';
export const AUTH_AUTHORIZATION_FAILED = 'AUTH_AUTHORIZATION_FAILED';
export const AUTH_AUTHORIZATION_SUCCESS = 'AUTH_AUTHORIZATION_SUCCESS';
export const AUTH_AUTHORIZATION_PENDING = 'AUTH_AUTHORIZATION_PENDING';

export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_PENDING = 'AUTH_LOGIN_PENDING';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';

export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_ERROR = 'AUTH_LOGOUT_ERROR';

// Notification action constants
export const NOTIFICATION_DISPLAY_ERROR = 'DISPLAY_ERROR';
export const NOTIFICATION_CONFIRM_RESET_PASSWORD = 'CONFIRM_RESET_PASSWORD';
export const NOTIFICATION_ADD = 'NOTIFICATION_ADD';
export const NOTIFICATION_REMOVE = 'NOTIFICATION_REMOVE';

// Modals
export const MODAL_CLOSE_MODAL = 'MODAL_CLOSE_MODAL';
export const MODAL_SET_MODAL = 'MODAL_SET_MODAL';
export const MODAL_SET_IMAGE_CONTEXT = 'MODAL_SET_IMAGE_CONTEXT';

// Request status
export const REQUEST_START = 'REQUEST_START';
export const REQUEST_END = 'REQUEST_END';
export const REQUEST_FAILED = 'REQUEST_FAILED';
